"""
Data Models for Report Management System

Purpose: Define the structure of data that flows through our API
- Request models: What frontend sends to backend
- Response models: What backend returns to frontend
- Database models: Not here (we use raw SQL), but these match our schema

Benefits of Pydantic:
1. Type safety: Catch bugs at development time
2. Automatic validation: Invalid data rejected before processing
3. Auto-generated docs: FastAPI uses these for OpenAPI/Swagger
4. Serialization: Easy conversion to/from JSON
"""

from pydantic import BaseModel, Field, validator
from typing import Optional, List
from datetime import datetime

# ==============================================================================
# REQUEST MODELS (Frontend → Backend)
# ==============================================================================
# These define what data the frontend must send to our API

class SaveReportRequest(BaseModel):
    """
    Data required to save a new report
    
    User flow:
    1. User asks question → gets results
    2. Clicks "Save Report" → modal appears
    3. Types report name, description, tags → submits
    4. Frontend sends this data to POST /reports/save
    
    Example JSON:
    {
        "report_name": "My Sales Dashboard",
        "user_question": "Show top 10 customers by sales",
        "generated_sql": "SELECT ... ORDER BY ... LIMIT 10",
        "report_description": "Monthly sales leaders report",
        "tags": ["sales", "monthly", "executive"]
    }
    """
    
    # Required fields (must be provided)
    report_name: str = Field(
        ...,  # ... means required
        min_length=1,
        max_length=255,
        description="User-provided name for the report",
        example="Top 10 Customers - December 2025"
    )
    
    user_question: str = Field(
        ...,
        min_length=1,
        description="Original natural language question",
        example="Show me top 10 customers by YTD sales"
    )
    
    generated_sql: str = Field(
        ...,
        min_length=1,
        description="SQL query generated by AI",
        example="SELECT ... FROM ... ORDER BY ..."
    )
    
    # Optional fields (can be null/missing)
    report_description: Optional[str] = Field(
        None,  # None = optional
        max_length=1000,
        description="Longer description of what the report shows",
        example="This report shows the top revenue-generating customers"
    )
    
    tags: Optional[List[str]] = Field(
        default=[],  # Default to empty list if not provided
        description="Categorization tags",
        example=["sales", "customers", "executive"]
    )
    
    # Custom validation: ensure report name isn't just whitespace
    @validator('report_name')
    def name_not_empty(cls, v):
        """Validator: Report name cannot be only spaces"""
        if not v.strip():
            raise ValueError('Report name cannot be empty or whitespace')
        return v.strip()  # Remove leading/trailing spaces
    
    # Custom validation: ensure SQL is not empty
    @validator('generated_sql')
    def sql_not_empty(cls, v):
        """Validator: SQL cannot be empty"""
        if not v.strip():
            raise ValueError('Generated SQL cannot be empty')
        return v.strip()
    
    # Custom validation: limit number of tags
    @validator('tags')
    def limit_tags(cls, v):
        """Validator: Maximum 10 tags per report"""
        if v and len(v) > 10:
            raise ValueError('Maximum 10 tags allowed')
        return v
    
    class Config:
        """Pydantic configuration"""
        # Allow creating model from ORM objects (if we use SQLAlchemy ORM later)
        orm_mode = True
        # Example for API docs
        schema_extra = {
            "example": {
                "report_name": "Monthly Sales Leaders",
                "user_question": "Who are the top 10 customers by sales?",
                "generated_sql": "SELECT gws_cust_code, SUM(gws_ytd_sales) FROM gwanalytics GROUP BY gws_cust_code LIMIT 10",
                "report_description": "Top performing customers this month",
                "tags": ["sales", "monthly"]
            }
        }


class ExecuteReportRequest(BaseModel):
    """
    Parameters for executing a saved report
    
    User flow:
    1. User clicks on a saved report
    2. Frontend calls POST /reports/{id}/execute
    3. Backend runs the SQL and returns fresh data
    """
    
    max_rows: int = Field(
        default=500,
        ge=1,      # ge = greater than or equal to
        le=10000,  # le = less than or equal to
        description="Maximum number of rows to return",
        example=500
    )
    
    # Future: Could add parameters like date filters, etc.
    # filters: Optional[Dict[str, Any]] = None


class UpdateReportRequest(BaseModel):
    """
    Data for updating an existing report
    All fields optional - only update what's provided
    
    User flow:
    1. User edits report name/description/tags
    2. Frontend sends PATCH /reports/{id}
    """
    
    report_name: Optional[str] = Field(
        None,
        min_length=1,
        max_length=255,
        description="New report name"
    )
    
    report_description: Optional[str] = Field(
        None,
        max_length=1000,
        description="New report description"
    )
    
    tags: Optional[List[str]] = Field(
        None,
        description="New tags (replaces existing)"
    )
    
    is_favorite: Optional[bool] = Field(
        None,
        description="Mark as favorite"
    )


# ==============================================================================
# RESPONSE MODELS (Backend → Frontend)
# ==============================================================================
# These define what data our API returns

class ReportResponse(BaseModel):
    """
    Complete report information returned by API
    
    Used by:
    - GET /reports/{id} - Get single report
    - POST /reports/save - After saving (returns created report)
    
    Example response:
    {
        "report_id": 42,
        "report_name": "My Sales Dashboard",
        "user_question": "Show top 10 customers",
        "generated_sql": "SELECT ...",
        "created_at": "2025-12-15T10:30:00",
        "last_executed_at": "2025-12-15T11:45:00",
        "execution_count": 5,
        "is_favorite": false,
        "tags": ["sales", "monthly"]
    }
    """
    
    report_id: int = Field(
        ...,
        description="Unique identifier for the report",
        example=42
    )
    
    report_name: str = Field(
        ...,
        description="User-provided report name",
        example="Monthly Sales Leaders"
    )
    
    user_question: str = Field(
        ...,
        description="Original natural language question",
        example="Show top 10 customers by sales"
    )
    
    generated_sql: str = Field(
        ...,
        description="SQL query generated by AI",
        example="SELECT ... FROM ..."
    )
    
    report_description: Optional[str] = Field(
        None,
        description="Report description",
        example="Top performing customers this month"
    )
    
    created_at: datetime = Field(
        ...,
        description="When the report was created",
        example="2025-12-15T10:30:00"
    )
    
    updated_at: Optional[datetime] = Field(
        None,
        description="When the report was last updated"
    )
    
    last_executed_at: Optional[datetime] = Field(
        None,
        description="When the report was last run"
    )
    
    execution_count: int = Field(
        default=0,
        description="How many times this report has been executed",
        example=5
    )
    
    is_favorite: bool = Field(
        default=False,
        description="Whether user marked this as favorite"
    )
    
    tags: List[str] = Field(
        default=[],
        description="Categorization tags",
        example=["sales", "monthly", "executive"]
    )
    
    status: str = Field(
        default="active",
        description="Report status",
        example="active"
    )
    
    class Config:
        orm_mode = True  # Allow creating from database rows


class ReportListItem(BaseModel):
    """
    Abbreviated report info for list views
    
    Used by: GET /reports - List all reports
    
    Why separate from ReportResponse?
    - Lighter weight (no SQL, no description)
    - Faster to load when showing many reports
    - User can click on a report to get full details
      
    Example:
    {
        "report_id": 42,
        "report_name": "Monthly Sales Leaders",
        "created_at": "2025-12-15T10:30:00",
        "last_executed_at": "2025-12-15T11:45:00",
        "execution_count": 5,
        "is_favorite": false,
        "tags": ["sales"]
    }
    """
    
    report_id: int
    report_name: str
    created_at: datetime
    last_executed_at: Optional[datetime]
    execution_count: int
    is_favorite: bool
    tags: List[str]
    
    class Config:
        orm_mode = True


class ReportListResponse(BaseModel):
    """
    Paginated list of reports
    
    Used by: GET /reports?limit=20&offset=0
    
    Example:
    {
        "reports": [...],  // Array of ReportListItem
        "total": 156,      // Total number of user's reports
        "limit": 20,       // How many per page
        "offset": 0        // Current page offset
    }
    """
    
    reports: List[ReportListItem] = Field(
        ...,
        description="List of reports"
    )
    
    total: int = Field(
        ...,
        description="Total number of reports (for pagination)",
        example=156
    )
    
    limit: int = Field(
        default=20,
        description="Number of reports per page",
        example=20
    )
    
    offset: int = Field(
        default=0,
        description="Offset for pagination",
        example=0
    )


class ExecuteReportResponse(BaseModel):
    """
    Result of executing a saved report
    
    Used by: POST /reports/{id}/execute
    
    Returns both report metadata and query results
    
    Example:
    {
        "report": {...},           // Full ReportResponse
        "rows": [...],             // Query results
        "row_count": 10,
        "execution_time_ms": 45
    }
    """
    
    report: ReportResponse = Field(
        ...,
        description="Report metadata"
    )
    
    rows: List[dict] = Field(
        ...,
        description="Query results",
        example=[
            {"customer": "ABC Corp", "sales": 50000},
            {"customer": "XYZ Ltd", "sales": 45000}
        ]
    )
    
    row_count: int = Field(
        ...,
        description="Number of rows returned",
        example=10
    )
    
    execution_time_ms: Optional[int] = Field(
        None,
        description="How long the query took (milliseconds)",
        example=45
    )


class SaveReportResponse(BaseModel):
    """
    Response after successfully saving a report
    
    Used by: POST /reports/save
    
    Example:
    {
        "report_id": 42,
        "message": "Report saved successfully"
    }
    """
    
    report_id: int = Field(
        ...,
        description="ID of newly created report",
        example=42
    )
    
    message: str = Field(
        default="Report saved successfully",
        description="Success message"
    )


class DeleteReportResponse(BaseModel):
    """
    Response after deleting a report
    
    Used by: DELETE /reports/{id}
    """
    
    message: str = Field(
        default="Report deleted successfully",
        description="Success message"
    )
    
    deleted_report_id: int = Field(
        ...,
        description="ID of deleted report",
        example=42
    )


class ErrorResponse(BaseModel):
    """
    Standard error response format
    
    FastAPI automatically uses this for HTTPExceptions
    
    Example:
    {
        "detail": "Report not found",
        "error_code": "REPORT_NOT_FOUND"
    }
    """
    
    detail: str = Field(
        ...,
        description="Human-readable error message",
        example="Report not found"
    )
    
    error_code: Optional[str] = Field(
        None,
        description="Machine-readable error code",
        example="REPORT_NOT_FOUND"
    )


# ==============================================================================
# UTILITY FUNCTIONS
# ==============================================================================

def database_row_to_report_response(row: dict) -> ReportResponse:
    """
    Convert database row to ReportResponse model
    
    Why needed? Database returns dict, we want typed Pydantic model
    
    Usage:
        row = db.fetch_one("SELECT * FROM saved_reports WHERE id=1")
        report = database_row_to_report_response(row)
        return report  # FastAPI auto-converts to JSON
    """
    return ReportResponse(
        report_id=row['report_id'],
        report_name=row['report_name'],
        user_question=row['user_question'],
        generated_sql=row['generated_sql'],
        report_description=row.get('report_description'),
        created_at=row['created_at'],
        updated_at=row.get('updated_at'),
        last_executed_at=row.get('last_executed_at'),
        execution_count=row.get('execution_count', 0),
        is_favorite=row.get('is_favorite', False),
        tags=row.get('tags', []),
        status=row.get('status', 'active')
    )


# ==============================================================================
# TYPE ALIASES (for better code readability)
# ==============================================================================

# Instead of writing List[dict] everywhere, use:
QueryResults = List[dict]

# Example usage:
# def execute_query(sql: str) -> QueryResults:
#     ...

